# Configuración del Servidor
server.port=8080

# Configuración de Correo (Ejemplo con Mailtrap)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=TU_USUARIO_AQUI
spring.mail.password=TU_PASSWORD_AQUI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.com.example.notification=DEBUG
